# Generated by Django 2.2.3 on 2019-07-13 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lider',
                'verbose_name_plural': 'Lideres',
                'db_table': 'app_leader',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'db_table': 'app_neighborhood',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(help_text='Identificación unica', max_length=10, unique=True, verbose_name='Identificación')),
                ('celphone', models.CharField(max_length=12, verbose_name='Telefono celular')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefono fijo')),
                ('name', models.CharField(max_length=150, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('rh', models.CharField(blank=True, max_length=3, null=True)),
                ('addres', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Fecha de cumpleaños')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('date_meeting', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de reunión')),
                ('state', models.BooleanField(default=False, verbose_name='Estado')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Leader', verbose_name='Lider')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Neighborhood', verbose_name='Barrio')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'app_person',
                'ordering': ('-last_name',),
            },
        ),
    ]
